### ISSUE TITLE
Create Search tool 👍 :

### ISSUE THREAD

**Issue by Pilloweye** [CodeChrisB/Jack-Mod-Box#13]
Create Search Tool for custom editor 👍

**Comment by CodeChrisB** [comment]
Like looking through all values in all fields and only showing these where your desired text was found. Got it.

**Comment by CodeChrisB** [comment]
The search tool will be expanded to a search and filter  tool
it will have a text field for the text search
and a **custom checkbox with 3 states** for every prop
**off**--> ignore this prop
**on**--> search text value in this prop
**ignore** --> do not even show this prop in the custom editor

and a normal checkbox --> show already modded prompts

**Comment by CodeChrisB** [comment]
## Current State in an Example
### We currently see 3 Inputs Id,IsValid,Phrase
## But I do only care about Phrase

![image](https://user-images.githubusercontent.com/55576076/226066533-ebd31d36-e27f-4a1d-9ebf-f8e4fe8210ed.png)

## So we use the new CustomCheckboxes to ignore those fields
![image](https://user-images.githubusercontent.com/55576076/226066645-d71e40d2-79b5-4d4e-bcf0-01c60a32c408.png)


The X you can see in the Filter Menu is a boolean field ,which currently is not implemented
